/*change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pizzaria;

import com.pizzaria.apresentacao.pedido.VisualizarPedidoView;
import com.pizzaria.apresentacao.produto.CadastrarProdutoView;
import com.pizzaria.apresentacao.cliente.CadastrarClienteView;
import com.pizzaria.apresentacao.entregador.EntregarPedidoView;
import com.pizzaria.apresentacao.pedido.CadastrarPedidoView;
import com.pizzaria.apresentacao.usuario.CadastrarUsuarioView;
import com.pizzaria.dto.UsuarioDTO;
import com.pizzaria.regrasNegocio.UsuarioRN;
import com.pizzaria.utilitarios.Utils;
import java.util.Arrays;
import javax.swing.JOptionPane;


/**
 *
 * @author Angelmário
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form StartJFrame
     */   
    public App() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();
        menuCadastroUsuarios = new javax.swing.JMenu();
        menuItemFuncionario = new javax.swing.JMenuItem();
        menuItemCliente = new javax.swing.JMenuItem();
        menuCadastrarPedido = new javax.swing.JMenu();
        menuCadastrarProduto = new javax.swing.JMenu();
        menuVisualizarPedidos = new javax.swing.JMenu();
        menuEntregarPedidos = new javax.swing.JMenu();
        //////
         setMaximumSize(new java.awt.Dimension(817, 508));
        setMinimumSize(new java.awt.Dimension(817, 508));
        setPreferredSize(new java.awt.Dimension(817, 508));
         jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArquivo.setText("Arquivo");

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        
        menuArquivo.add(sair);
        menu.add(menuArquivo);
        

        menuCadastroUsuarios.setText("Cadastro de usuários");

        menuItemFuncionario.setText("Funcionário");
        menuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionarioActionPerformed(evt);
            }
        });
       

        menuItemCliente.setText("Cliente");
        menuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClienteActionPerformed(evt);
            }
        });
       

        
        menuCadastroUsuarios.getAccessibleContext().setAccessibleDescription("");

        menuCadastrarPedido.setText("Cadastrar pedido");
        menuCadastrarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastrarPedidoMouseClicked(evt);
            }
        });
        

        menuCadastrarProduto.setText("Cadastrar produto");
        menuCadastrarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCadastrarProdutoMouseClicked(evt);
            }
        });
        

        menuVisualizarPedidos.setText("Visualizar pedidos");
        menuVisualizarPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuVisualizarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVisualizarPedidosMouseClicked(evt);
            }
        });
        

        menuEntregarPedidos.setText("Entregar pedidos");
        menuEntregarPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuEntregarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEntregarPedidosMouseClicked(evt);
            }
        });
//        menuCadastroUsuarios.add(menuItemFuncionario);
//        menuCadastroUsuarios.add(menuItemCliente);
//        menu.add(menuArquivo);
//        menu.add(menuCadastroUsuarios);
//        menu.add(menuCadastrarPedido);
//        menu.add(menuCadastrarProduto);
//        menu.add(menuVisualizarPedidos);
//        menu.add(menuEntregarPedidos);
        
        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        
       //////////////////////////////////////////////

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogin.setText("Login:");

        lblSenha.setText("Senha:");

        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitulo.setText("Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEntrar)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblTitulo)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblTitulo)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEntrar)
                .addContainerGap(117, Short.MAX_VALUE))
        );

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );


        pack();
    }// </editor-fold>                        

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {                                     
        System.exit(0);
    }                                    

    private void menuVisualizarPedidosMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        this.setContentPane(new VisualizarPedidoView());  
        this.pack();
    }                                                  

    private void menuCadastrarPedidoMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        this.setContentPane(new CadastrarPedidoView());  
        this.pack();
    }                                                

    private void menuCadastrarProdutoMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        this.setContentPane(new CadastrarProdutoView());  
        this.pack();
    }                                                 

    private void menuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                
        this.setContentPane(new CadastrarClienteView());  
        this.pack();
    }                                               

    private void menuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.setContentPane(new CadastrarUsuarioView());  
        this.pack();
    }           
    
     private void menuEntregarPedidosMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        this.setContentPane(new EntregarPedidoView());  
        this.pack();
    }                 

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {    
        UsuarioRN u = new UsuarioRN();
        UsuarioDTO usr = null;
        try{
            usr = (UsuarioDTO) u.autenticar(txtLogin.getText(), Arrays.toString(txtSenha.getPassword()));
        } catch (Exception e) {
            usr = null;
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção",  JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if(Utils.isNullOrEmpty(usr)){
            return;
        }
        
        if("ADMINISTRADOR".equalsIgnoreCase(usr.getTipo().getDescricao())){
            menuCadastroUsuarios.add(menuItemFuncionario);
            menuCadastroUsuarios.add(menuItemCliente);
            menu.add(menuCadastroUsuarios);
            menu.add(menuCadastrarPedido);
            menu.add(menuCadastrarProduto);
            menu.add(menuVisualizarPedidos);
            menu.add(menuEntregarPedidos);            
        }else if("ATENDENTE".equalsIgnoreCase(usr.getTipo().getDescricao())){            
            menuCadastroUsuarios.add(menuItemCliente);
            menu.add(menuCadastroUsuarios);
            menu.add(menuCadastrarPedido);                         
        }else if("PIZZAIOLO".equalsIgnoreCase(usr.getTipo().getDescricao())){            
            menu.add(menuVisualizarPedidos);            
        }else if("ENTREGADOR".equalsIgnoreCase(usr.getTipo().getDescricao())){
            menu.add(menuEntregarPedidos);            
        }
        this.setContentPane(new Welcome(usr.getNome()));
        setJMenuBar(menu);
        pack();
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastrarPedido;
    private javax.swing.JMenu menuCadastrarProduto;
    private javax.swing.JMenu menuCadastroUsuarios;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemFuncionario;
    private javax.swing.JMenu menuVisualizarPedidos;
    private javax.swing.JMenu menuEntregarPedidos;
    private javax.swing.JMenuItem sair;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration                   
}