/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pizzaria;

/**
 *
 * @author Angelmário
 */
public class Welcome extends javax.swing.JPanel {

    /**
     * Creates new form Welcome
     * @param nome
     */
    public Welcome(String nome) {
        initComponents();
        lblBemVindo.setText("Bem vindo(a) " + nome + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemVindo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(817, 508));
        setMinimumSize(new java.awt.Dimension(817, 508));

        lblBemVindo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblBemVindo.setText("Bem vindo!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBemVindo)
                .addContainerGap(688, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBemVindo)
                .addContainerGap(468, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBemVindo;
    // End of variables declaration//GEN-END:variables
}
