/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pizzaria.apresentacao.pedido;

import com.pizzaria.dto.BaseDTO;
import com.pizzaria.dto.PedidoDTO;
import com.pizzaria.regrasNegocio.PedidoRN;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelmário
 *  Classe criada para tela de Visualização da tabela Pedidos
 */
public class VisualizarPedidoView extends javax.swing.JPanel {

    /**
     * Creates new form VisualizarPedidoView
     */
    public VisualizarPedidoView() {
        initComponents();
        carregarPedidos();
       
    }
    
    private void carregarPedidos(){
         PedidoRN pedidoRN = new PedidoRN();
         PedidoTableModel modelo = new PedidoTableModel();
         try{
            for (BaseDTO b : pedidoRN.obterPedidosPendentes()) {
               modelo.addPedido(((PedidoDTO) b));
            }
          } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção",  JOptionPane.INFORMATION_MESSAGE);
        }

        tblPedidos.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEncaminhar = new javax.swing.JButton();
        lblVisualizarEncaminharPedidos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();

        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(817, 508));
        setMinimumSize(new java.awt.Dimension(817, 508));
        setPreferredSize(new java.awt.Dimension(817, 508));

        btnEncaminhar.setText("Encaminhar");
        btnEncaminhar.setToolTipText("");
        btnEncaminhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncaminharMouseClicked(evt);
            }
        });

        lblVisualizarEncaminharPedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVisualizarEncaminharPedidos.setText("Visualizar/Encaminhar pedidos");

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPedidos);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVisualizarEncaminharPedidos)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(lblVisualizarEncaminharPedidos)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEncaminhar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncaminharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncaminharMouseClicked

           PedidoRN pedidoRN = new PedidoRN();
            
            try{
                for (Integer index : tblPedidos.getSelectedRows()) {                    
                    PedidoDTO p = ((PedidoTableModel) tblPedidos.getModel()).getPedido(index);
                    Timestamp datahoje = new Timestamp(System.currentTimeMillis());
                    p.setPedidoPronto(Boolean.TRUE);
                    p.setTimeInsert(datahoje);
                    pedidoRN.atualizarPedido(p);
                }
            carregarPedidos();
            }catch(Exception e){
                 e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção",  JOptionPane.INFORMATION_MESSAGE);
            }
                    
        
    }//GEN-LAST:event_btnEncaminharMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncaminhar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblVisualizarEncaminharPedidos;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
